### ISSUE TITLE
Outdated ha-bridge version for latest image

### ISSUE THREAD

**Issue by Neonox31** [tsgoff/docker-alexa-ha-bridge#1]
The last built docker image pointing on v4.5.1 of ha-bridge instead of the latest release : v4.5.6.

@tsgoff : Could you enforce a rebuilt please ?

**Comment by tsgoff** [comment]
Hi Neonox31, fixed: bios/docker-alexa-ha-bridge:v4.5.6

**Comment by Neonox31** [comment]
Thanks a lot !
