### ISSUE TITLE
HA-Bridge 5.2.0

### ISSUE THREAD

**Issue by hvorragend** [tsgoff/docker-alexa-ha-bridge#4]
I do not really have an explanation for that.
But when I rebuild the containers and images, the version always stays at 5.1.0. But since yesterday 5.2.0 is out.

If I manually execute the commands in the Dockerfile, it works. So the syntax is ok.

Of course I completely deleted images and containers.

It there something I can do? Or is this related with some DockerHub-stuff?

---

I did not know that you have to rebuild the images. I assumed that the images are generated in real-time on my docker-host.

**Comment by tsgoff** [comment]
When you build the conainer you get always the latest version.
You can now pull the latest version from the hub with bios/docker-alexa-ha-bridge:latest or bios/docker-alexa-ha-bridge:v5.2.0

docker run --name bridge -d -p 8080:8080 -e PORT="-Dserver.port=8080" -e KEY="-Dsecurity.key=Xfawer354WertSdf321234asd" -e GARDEN="-Dexec.garden=/bridge/" bios/docker-alexa-ha-bridge:latest

**Comment by hvorragend** [comment]
Thank you very much.

**Comment by hvorragend** [comment]
Could you please tag 5.2.1, too?
Thanx

**Comment by tsgoff** [comment]
is running
